title: Page
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  sectionsLeft:
    label: Sections left
    type: structure
    style: table
    fields: 
      title: 
        label: Title
        type: text
      text: 
        label: Text
        type: textarea
  sectionsRight:
    label: Sections right
    type: structure
    style: table
    fields: 
      title: 
        label: Title
        type: text
      text: 
        label: Text
        type: textarea